In [2]:
import pandas as pd
df=pd.read_csv('Indian_election_dataset.csv')
df.info()

df=df.drop(['pc_no','pc_name','partyabbre'],axis=1)
df=df.drop_duplicates()
df=df.rename(columns={'st_name':'state','cand_name':'candidate','partyname':'party_name','totvotpoll':'tot_vot_poll'})
df=df.dropna(subset=(['state','year']))
df=df.dropna(subset=(['cand_sex','party_name']))
df['electors']=df['electors'].fillna(df['electors'].median())
df=df.rename(columns={'pc_type':'reservation_category'})
df['year']=df['year'].astype(int)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73181 entries, 0 to 73180
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   st_name     69594 non-null  object
 1   year        69495 non-null  float64
 2   pc_no       69591 non-null  float64
 3   pc_name     69643 non-null  object
 4   pc_type     61815 non-null  object
 5   cand_name   69568 non-null  object
 6   cand_sex    68987 non-null  object
 7   partyname   69605 non-null  object
 8   partyabbre  69618 non-null  object
 9   totvotpoll  69608 non-null  float64
 10  electors    69437 non-null  float64
dtypes: float64(4), object(7)
memory usage: 6.1+ MB

0        1977
1        1977
3        1980
4        1980
5        1980
         ...
73075    2014
73077    2014
73078    2014
73079    2014
73080    2014
Name: year, Length: 59221, dtype: int32

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 59221 entries, 0 to 73080
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   state                 59221 non-null  object
 1   year                  59221 non-null  float64
 2   reservation_category  49977 non-null  object
 3   candidate             56296 non-null  object
 4   cand_sex              59221 non-null  object
 5   party_name            59221 non-null  object
 6   tot_vot_poll          56338 non-null  float64
 7   electors              59221 non-null  float64
dtypes: float64(3), object(5)
memory usage: 4.1+ MB

In [6]:
df

,state,year,reservation_category,candidate,cand_sex,party_name,tot_vot_poll,electors
0,Andaman & Nicobar Islands,1977.0,GEN,K.R. Ganesh,Male,independents,25168.0,1097550.0
1,Andaman & Nicobar Islands,1977.0,GEN,Manoranjan Bhakta,Male,indian_national_congress,35400.0,85308.0
3,Andaman & Nicobar Islands,1980.0,GEN,Alagiri Swamy,Male,independents,NaN,96084.0
4,Andaman & Nicobar Islands,1980.0,GEN,Kannu Chemy,Male,independents,405.0,96084.0
5,Andaman & Nicobar Islands,1980.0,GEN,K.N. Raju,Male,independents,470.0,96084.0
...,...,...,...,...,...,...,...,...
73075,West Bengal,2014.0,GEN,Shibratan Sharma,Male,jmm,7989.0,1495089.0
73077,West Bengal,2014.0,GEN,Syed Siraj Jimmi,Male,inc,132084.0,1495089.0
73078,West Bengal,2014.0,GEN,Joy Banerjee,Male,bjp,235753.0,1495089.0
73079,West Bengal,2014.0,GEN,Dr. Elahi Kamre Mahammad,Male,cpm,393305.0,1495089.0
73080,West Bengal,2014.0,GEN,Satabdi Roy,F,aitc,460568.0,1495089.0

In [8]:
df['year']=df['year'].astype(int)

In [10]:
df

,state,year,reservation_category,candidate,cand_sex,party_name,tot_vot_poll,electors
0,Andaman & Nicobar Islands,1977,GEN,K.R. Ganesh,Male,independents,25168.0,1097550.0
1,Andaman & Nicobar Islands,1977,GEN,Manoranjan Bhakta,Male,indian_national_congress,35400.0,85308.0
3,Andaman & Nicobar Islands,1980,GEN,Alagiri Swamy,Male,independents,NaN,96084.0
4,Andaman & Nicobar Islands,1980,GEN,Kannu Chemy,Male,independents,405.0,96084.0
5,Andaman & Nicobar Islands,1980,GEN,K.N. Raju,Male,independents,470.0,96084.0
...,...,...,...,...,...,...,...,...
73075,West Bengal,2014,GEN,Shibratan Sharma,Male,jmm,7989.0,1495089.0
73077,West Bengal,2014,GEN,Syed Siraj Jimmi,Male,inc,132084.0,1495089.0
73078,West Bengal,2014,GEN,Joy Banerjee,Male,bjp,235753.0,1495089.0
73079,West Bengal,2014,GEN,Dr. Elahi Kamre Mahammad,Male,cpm,393305.0,1495089.0
73080,West Bengal,2014,GEN,Satabdi Roy,F,aitc,460568.0,1495089.0

In [16]:
df.cand_sex.values

array(['Male', 'Male', 'Male', ..., 'Male', 'Male', 'Female'],
      dtype=object)

In [14]:
df['cand_sex']=df['cand_sex'].str.replace('F','Female')

In [23]:
df.sample(10)

,state,year,reservation_category,candidate,cand_sex,party_name,tot_vot_poll,electors
71746,West Bengal,1999,GEN,Sisir Kumar Sen,Male,indian_national_congress,71978.0,1101065.0
45455,Punjab,2014,GEN,Harish Kumar,Male,shs,2325.0,1580273.0
23845,Karnataka,1996,GEN,R B Guttal,Male,independent,225.0,1300498.0
8920,Bihar,1991,GEN,NaN,Male,independent,98.0,976411.0
38249,Maharashtra,2009,NaN,Sanjay Dina Patil,Male,nationalist_congress_party,213505.0,1097550.0
37634,Maharashtra,2004,GEN,Shaikh Akhil Usman,Male,ind,5487.0,1319891.0
29396,Madhya Pradesh,1991,GEN,Ram Krishna,Male,independent,6298.0,1018753.0
28141,Madhya Pradesh,1980,NaN,Ramal Das,Male,republican_party_of_india_(khobragade),7623.0,592243.0
38346,Maharashtra,2009,NaN,Shaikh Altaf Karim,Male,independent,595.0,1806953.0
6065,Assam,1999,GEN,Mira Borthakur,Female,rashtriya_janata_dal,1818.0,1111536.0

In [27]:
df['reservation_category']=df['reservation_category'].fillna('OTHERS')

In [29]:
df=df.drop('candidate',axis=1)

In [33]:
df['tot_vot_poll']=df['tot_vot_poll'].fillna(df['tot_vot_poll'].median())

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 59221 entries, 0 to 73080
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   state                 59221 non-null  object
 1   year                  59221 non-null  int32
 2   reservation_category  59221 non-null  object
 3   cand_sex              59221 non-null  object
 4   party_name            59221 non-null  object
 5   tot_vot_poll          59221 non-null  float64
 6   electors              59221 non-null  float64
dtypes: float64(2), int32(1), object(4)
memory usage: 3.4+ MB

In [37]:
df.to_csv('election_cleaned_data.csv',index=False)